### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by croccio** [blackwiz4rd/Vodafone-WiFi-AutoLogin#1]
potresti farlo anche per linux?

**Comment by blackwiz4rd** [comment]
Non so se funzioni perchè non ho linux per provarlo ma ho aggiunto una funzione per usarlo su linux al nuovo script caricato (usa solo quello con `python vodafone-wifi-linux.py`).
Fammi sapere se funziona (Ricorda di seguire le istruzioni del readme).

https://github.com/blackwiz4rd/Vodafone-WiFi-AutoLogin/blob/master/vodafone-wifi-linux.py

**Comment by croccio** [comment]
mi da il seguente errore 

```
vodafone-wifi-linux.py: 13: vodafone-wifi-linux.py: import: not found
from: can't read /var/mail/os.path
from: can't read /var/mail/time
from: can't read /var/mail/subprocess
vodafone-wifi-linux.py: 19: vodafone-wifi-linux.py: Syntax error: "(" unexpected

```

**Comment by blackwiz4rd** [comment]
> mi da il seguente errore
> 
> vodafone-wifi-linux.py: 13: vodafone-wifi-linux.py: import: not found
> from: can't read /var/mail/os.path
> from: can't read /var/mail/time
> from: can't read /var/mail/subprocess
> vodafone-wifi-linux.py: 19: vodafone-wifi-linux.py: Syntax error: "(" unexpected

Deve installare "requests".
Le consiglio di farlo tramite pip (https://pip.pypa.io/en/stable/installing/). Dopo aver eseguito `python get-pip.py`, esegua `pip install requests`.
Infine per eseguire il mio script usi
`python vodafone-wifi-linux.py`
Si assicuri di non averlo eseguito con `sh vodafone-wifi-linux.py`.

**Comment by blackwiz4rd** [comment]
Ho aggiornato la guida specificando che `input.txt` va messo nella stessa directory dello script (con quello aggiornato). Lo script aggiornato è utilizzabile su windows,linux e MacOS. Mi faccia sapere se ci sono problemi.

**Comment by croccio** [comment]
mi da questo errore 
`
ValueError: Timeout value connect was (10, 10), but it must be an int or float.`

eliminando il timeout va

**Comment by blackwiz4rd** [comment]
Forse avevo usato una versione di requests più vecchia, controlli adesso con il nuovo codice se vuole.
