### ISSUE TITLE
OpenWrt

### ISSUE THREAD

**Issue by ltedone** [blackwiz4rd/Vodafone-WiFi-AutoLogin#2]
Ciao,
è possibile aggiungere le istruzioni per far girare questo script su OperWrt?

Grazie

**Comment by blackwiz4rd** [comment]
Scusami se rispondo solo adesso. Penso sia possibile ma dipende dalla quantità di memoria in MB disponibile sul router perchè bisognerebbe installare python. L'ideale sarebbe riprogrammare le funzioni in C, in modo che si possa creare un programma più leggero.

**Comment by malesci** [comment]
> Scusami se rispondo solo adesso. Penso sia possibile ma dipende dalla quantità di memoria in MB disponibile sul router perchè bisognerebbe installare python. L'ideale sarebbe riprogrammare le funzioni in C, in modo che si possa creare un programma più leggero.

Ciao, avendo un router con abbastanza memoria per consentire l'installazione di python, serve sempre che alla prima esecuzione il dispositivo dia già connesso a Vodafone-wifi con tanto di accesso alla landing page e l'inserimento dee credenziali? Non sono sicuro ma ho letto che la Vodafone station registra i mac da autorizzare.

**Comment by blackwiz4rd** [comment]
Per OpenWrt consiglio l'uso di questo tool: https://github.com/schiavonedimitri/Vodafone-WiFi

**Comment by pilovis** [comment]
> Per OpenWrt consiglio l'uso di questo tool: https://github.com/schiavonedimitri/Vodafone-WiFi

sicuramente per openwrt va meglio, molto piu' leggero e non ha bisogno di installare phyton

**Comment by pilovis** [comment]
> Ciao,
> è possibile aggiungere le istruzioni per far girare questo script su OperWrt?
> 
> Grazie

non servono particolari istruzioni, devi solo installare i moduli Python necessari con "opkg", ma hai bisogno di almeno 64 mega di RAM (con la Z-RAM attiva a 32 mega) e almeno 128 mega di Flash disponibile.

```
opkg update
opkg install zram-swap
opkg install python
opkg install python-pip

pip install requests
pip install configparser
pip install logging
```
