### ISSUE TITLE
Linux pc come router

### ISSUE THREAD

**Issue by malesci** [blackwiz4rd/Vodafone-WiFi-AutoLogin#4]
Complimenti ottimo script. Sarebbe possibile eseguirlo da una macchina Linux (Mint o Ubuntu per esempio) e fare comportare questa macchina come router di casa? 
Il PC ha scheda di rete eth che wlan.

**Comment by blackwiz4rd** [comment]
Teoricamente si, l'unico problema consiste nel fatto che ti servirebbe una doppia scheda wlan (potresti comprare un qualsiasi adattatore wifi/usb: https://www.ebay.it/sch/i.html?_from=R40&_trksid=m570.l1313&_nkw=usb+wifi&_sacat=0). In questo modo potresti condividere il WiFi da wlan1 (connesso a Vodafone-WiFi) a wlan2 (il tuo WiFi).

Un'alternativa è di utilizzare un ripetitore per ripetere Vodafone-WiFi e avviare lo script dal tuo PC o da un linux connesso al ripetitore. 
Se vuoi usare un router con OpenWrt c'è un esempio di configurazione qui: https://github.com/blackwiz4rd/OpenWrt-configurations/tree/master/etc/config/vodafone.
