### ISSUE TITLE
Login invalida con account name invece di email

### ISSUE THREAD

**Issue by malesci** [blackwiz4rd/Vodafone-WiFi-AutoLogin#5]
Ciao ho delle credenziali di accesso Vodafone WiFi, testate con successo da più dispositivi. Tuttavia il formato delle credenziali è del tipo 
username = your-account
password = your-password

Invece di 
username = your-account@your-provider.com
password = your-password

Lo script configurato con le credenziali in mio possesso (non ho una account email ma solo username) da errore di login per credenziali non valide. Ma se stesse credenziali funzionano egregiamente dal portale Vodafone.

**Comment by malesci** [comment]
A vantaggio di altri utenti che potrebbero incontrare il mio stesso problema, con l'aiuto del buon @blackwiz4rd che ringrazio abbiamo escluso che il problema sia dovuto al differente formato dello username. Potrebbe invece dipendere dagli ultimi check-in quindi al momento abbiamo risolto eseguendo un rollback della versione ad una precedente
git checkout 9422de0
Grazie

**Comment by blackwiz4rd** [comment]
Credo che i problemi siano dovuti alla riscrittura di alcune parti del programma nei commit:

- https://github.com/blackwiz4rd/Vodafone-WiFi-AutoLogin/commit/f86c3be0a38c07cd3ea035904fbc74c488b55ce9
- https://github.com/blackwiz4rd/Vodafone-WiFi-AutoLogin/commit/60073472988bf3940da93b9880b91244c8c40f0b

che purtroppo non riesco a verificare non disponendo di un Vodafone-WiFi al momento.

**Comment by blackwiz4rd** [comment]
Per facilitare gli altri utenti ho ripristinato il contenuto del commit `9422de0`.
